// The candidate device-code implementation.
//
// This is a reimplementation of the protocol the pinned Codex release speaks,
// not a port of its code. It is proprietary, not RFC 8628: JSON bodies rather
// than form encoding, a string-typed poll interval, 403/404 meaning "keep
// going" rather than a `authorization_pending` error code, and a PKCE pair
// supplied by the server rather than generated by the client.
//
// Two deliberate divergences from Codex, both safety-motivated and both
// reported rather than hidden:
//
//   1. An absent interval yields the default rather than Codex's 0, which would
//      poll as fast as the loop can run.
//   2. An unparsable interval is a permanent failure rather than a 0.
//
// Nothing here writes to the credential store. A failed flow must leave no
// trace, so persistence is the caller's decision and happens only on success.

import { createHash } from "node:crypto";

import type { Clock } from "../clock.ts";
import { AuthError } from "./errors.ts";
import {
  DEVICE_DEADLINE_SECONDS,
  DEVICE_INTERVAL_DEFAULT_MS,
  DEVICE_INTERVAL_FLOOR_MS,
  DEVICE_POLL_CONTINUE_STATUSES,
  DEVICE_REDIRECT_PATH,
  DEVICE_TOKEN_PATH,
  DEVICE_USERCODE_PATH,
  DEVICE_VERIFICATION_PATH,
  OAUTH_CLIENT_ID,
  OAUTH_TOKEN_PATH,
} from "../reference.ts";

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export type DeviceSession = {
  deviceAuthId: string;
  userCode: string;
  verificationUri: string;
  intervalMs: number;
};

export type DeviceAuthorization = {
  authorizationCode: string;
  codeVerifier: string;
  codeChallenge: string;
  polls: number;
};

export type TokenSet = {
  idToken: string;
  accessToken: string;
  refreshToken: string | null;
  expiresAtSeconds: number;
  accountId: string;
};

export type DeviceFlowOptions = {
  issuer: string;
  clientId?: string;
  clock: Clock;
  fetch: FetchLike;
  /** Overridable so a test can pin a shorter deadline; defaults to Codex's. */
  deadlineSeconds?: number;
};

export type DeviceFlowMetrics = {
  usercodeCalls: number;
  tokenCalls: number;
  exchangeCalls: number;
  intervalGaps: number[];
};

export class DeviceFlow {
  readonly metrics: DeviceFlowMetrics = {
    usercodeCalls: 0,
    tokenCalls: 0,
    exchangeCalls: 0,
    intervalGaps: [],
  };

  #options: Required<Omit<DeviceFlowOptions, "clientId">> & { clientId: string };

  constructor(options: DeviceFlowOptions) {
    this.#options = {
      issuer: options.issuer.replace(/\/+$/, ""),
      clientId: options.clientId ?? OAUTH_CLIENT_ID,
      clock: options.clock,
      fetch: options.fetch,
      deadlineSeconds: options.deadlineSeconds ?? DEVICE_DEADLINE_SECONDS,
    };
  }

  async initiate(): Promise<DeviceSession> {
    const { issuer, clientId, fetch } = this.#options;
    this.metrics.usercodeCalls += 1;

    let response: Response;
    try {
      response = await fetch(`${issuer}${DEVICE_USERCODE_PATH}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ client_id: clientId }),
      });
    } catch (cause) {
      throw new AuthError("NETWORK", `device initiation failed: ${describe(cause)}`);
    }

    if (!response.ok) {
      throw new AuthError(
        "DEVICE_DENIED",
        `device initiation rejected with status ${response.status}`,
      );
    }

    const payload = (await response.json()) as Record<string, unknown>;
    const deviceAuthId = firstString(payload, ["device_auth_id", "deviceAuthId"]);
    const userCode = firstString(payload, ["user_code", "usercode", "userCode"]);

    if (!deviceAuthId || !userCode) {
      throw new AuthError(
        "DEVICE_DENIED",
        "device initiation response is missing device_auth_id or user_code",
      );
    }

    return {
      deviceAuthId,
      userCode,
      verificationUri: `${issuer}${DEVICE_VERIFICATION_PATH}`,
      intervalMs: parseInterval(payload.interval),
    };
  }

  async poll(session: DeviceSession): Promise<DeviceAuthorization> {
    const { issuer, clock, fetch, deadlineSeconds } = this.#options;
    const deadline = clock.now() + deadlineSeconds * 1000;
    let polls = 0;

    for (;;) {
      // A poll whose slot has already passed the deadline is never issued.
      if (clock.now() >= deadline) {
        throw new AuthError(
          "DEVICE_TIMEOUT",
          `device authorization timed out after ${deadlineSeconds}s`,
        );
      }

      polls += 1;
      this.metrics.tokenCalls += 1;

      let response: Response;
      try {
        response = await fetch(`${issuer}${DEVICE_TOKEN_PATH}`, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            device_auth_id: session.deviceAuthId,
            user_code: session.userCode,
          }),
        });
      } catch (cause) {
        throw new AuthError("NETWORK", `device polling failed: ${describe(cause)}`);
      }

      if (response.ok) {
        const payload = (await response.json()) as Record<string, unknown>;
        const authorizationCode = firstString(payload, ["authorization_code"]);
        const codeVerifier = firstString(payload, ["code_verifier"]);
        const codeChallenge = firstString(payload, ["code_challenge"]);

        if (!authorizationCode || !codeVerifier || !codeChallenge) {
          throw new AuthError(
            "DEVICE_DENIED",
            "device authorization response is missing the code or PKCE pair",
          );
        }

        // The server supplies the PKCE pair, so the client's only leverage is
        // to check that it is internally consistent before spending the code.
        if (s256(codeVerifier) !== codeChallenge) {
          throw new AuthError(
            "PKCE_MISMATCH",
            "device authorization PKCE verifier does not derive the challenge",
          );
        }

        return { authorizationCode, codeVerifier, codeChallenge, polls };
      }

      if (!DEVICE_POLL_CONTINUE_STATUSES.includes(response.status)) {
        if (response.status >= 500) {
          throw new AuthError(
            "UPSTREAM_5XX",
            `device polling failed with status ${response.status}`,
          );
        }
        throw new AuthError(
          "DEVICE_DENIED",
          `device polling rejected with status ${response.status}`,
        );
      }

      const remaining = deadline - clock.now();
      if (remaining <= 0) {
        throw new AuthError(
          "DEVICE_TIMEOUT",
          `device authorization timed out after ${deadlineSeconds}s`,
        );
      }

      const gap = Math.min(session.intervalMs, remaining);
      this.metrics.intervalGaps.push(gap);
      await clock.sleep(gap);
    }
  }

  async exchange(authorization: DeviceAuthorization): Promise<TokenSet> {
    const { issuer, clientId, clock, fetch } = this.#options;
    this.metrics.exchangeCalls += 1;

    const body = new URLSearchParams({
      grant_type: "authorization_code",
      code: authorization.authorizationCode,
      redirect_uri: `${issuer}${DEVICE_REDIRECT_PATH}`,
      client_id: clientId,
      code_verifier: authorization.codeVerifier,
    });

    let response: Response;
    try {
      response = await fetch(`${issuer}${OAUTH_TOKEN_PATH}`, {
        method: "POST",
        headers: { "content-type": "application/x-www-form-urlencoded" },
        body: body.toString(),
      });
    } catch (cause) {
      throw new AuthError("NETWORK", `code exchange failed: ${describe(cause)}`);
    }

    if (!response.ok) {
      throw new AuthError(
        "DEVICE_DENIED",
        `code exchange rejected with status ${response.status}`,
      );
    }

    const payload = (await response.json()) as Record<string, unknown>;
    const idToken = firstString(payload, ["id_token"]);
    const accessToken = firstString(payload, ["access_token"]);
    const refreshToken = firstString(payload, ["refresh_token"]);

    if (!idToken || !accessToken) {
      throw new AuthError("CLAIMS_INCOMPLETE", "code exchange returned no usable token pair");
    }

    const accountId = extractAccountId(idToken);
    if (!accountId) {
      throw new AuthError(
        "CLAIMS_INCOMPLETE",
        "id token carries no ChatGPT account claim",
      );
    }

    return {
      idToken,
      accessToken,
      refreshToken: refreshToken ?? null,
      expiresAtSeconds: expiryOf(accessToken, clock),
      accountId,
    };
  }
}

// ---------------------------------------------------------------------------

/**
 * Codex parses `interval` from a JSON string and tolerates its absence as 0.
 * The runtime accepts both the string and numeric spellings, applies a floor,
 * and refuses a value it cannot parse.
 */
export function parseInterval(raw: unknown): number {
  if (raw === undefined || raw === null) return DEVICE_INTERVAL_DEFAULT_MS;

  let seconds: number;
  if (typeof raw === "number") {
    seconds = raw;
  } else if (typeof raw === "string") {
    const trimmed = raw.trim();
    if (!/^\d+$/.test(trimmed)) {
      throw new AuthError("DEVICE_INTERVAL_INVALID", "device interval is not an integer");
    }
    seconds = Number.parseInt(trimmed, 10);
  } else {
    throw new AuthError("DEVICE_INTERVAL_INVALID", "device interval has an unusable type");
  }

  if (!Number.isFinite(seconds) || seconds < 0) {
    throw new AuthError("DEVICE_INTERVAL_INVALID", "device interval is out of range");
  }

  return Math.max(seconds * 1000, DEVICE_INTERVAL_FLOOR_MS);
}

export function s256(verifier: string): string {
  return createHash("sha256").update(verifier).digest("base64url");
}

/**
 * Decode-only. The signature is not verified, which is acceptable for a spike
 * because the token arrives over TLS from the issuer that minted it, but it is
 * a production gap and is recorded as one.
 */
export function decodeJwtPayload(token: string): Record<string, unknown> | null {
  const parts = token.split(".");
  if (parts.length < 2) return null;
  try {
    const json = Buffer.from(parts[1] as string, "base64url").toString("utf8");
    const parsed: unknown = JSON.parse(json);
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return null;
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

export function extractAccountId(idToken: string): string | null {
  const claims = decodeJwtPayload(idToken);
  if (!claims) return null;

  const auth = claims["https://api.openai.com/auth"];
  if (auth !== null && typeof auth === "object" && !Array.isArray(auth)) {
    const nested = (auth as Record<string, unknown>).chatgpt_account_id;
    if (typeof nested === "string" && nested.length > 0) return nested;
  }

  const flat = claims.chatgpt_account_id;
  return typeof flat === "string" && flat.length > 0 ? flat : null;
}

/** Prefer the access token's own `exp`; fall back to a conservative window. */
function expiryOf(accessToken: string, clock: Clock): number {
  const claims = decodeJwtPayload(accessToken);
  const exp = claims?.exp;
  if (typeof exp === "number" && Number.isFinite(exp)) return Math.floor(exp);
  return Math.floor(clock.now() / 1000) + 3600;
}

function firstString(
  payload: Record<string, unknown>,
  keys: readonly string[],
): string | null {
  for (const key of keys) {
    const value = payload[key];
    if (typeof value === "string" && value.length > 0) return value;
  }
  return null;
}

function describe(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}
